### ISSUE TITLE
Add support for additional file types in preferences.

### ISSUE THREAD

**Issue by jasonplatts** [jasonplatts/tailwindcss-nova-ext#10]
Support for additional file types, such as Twig and Svelte files is needed. A future update should provide the ability for users to change supported file types in global and workspace preferences.

**Comment by beornlake** [comment]
Just came here to request support for [Blade syntax](https://github.com/melvinbeemer/Blade.novaextension), so glad to see that additional file types is already on your radar. Thanks for putting this extension together!

**Comment by jasonplatts** [comment]
Thanks @beornlake. I’m glad that it’s helpful! This and more updates coming soon.

**Comment by jasonplatts** [comment]
> Just came here to request support for [Blade syntax](https://github.com/melvinbeemer/Blade.novaextension), so glad to see that additional file types is already on your radar. Thanks for putting this extension together!

@beornlake could you provide a blade syntax example or some additional context where classes are not being offered? I have tested a sample file and haven't noticed any issues with Tailwind autosuggestions failing to display. However, I am not familiar with Blade syntax, so it is absolutely possible that I am missing something.

**Comment by beornlake** [comment]
A Blade file is very similar to a PHP-HTML file, but it does not start with the `<?php` keyword, and has some extra elements. There are special `@` directives and `{{ }}` sequences that trigger PHP syntax. If I set my file type to PHP-HTML, then the Tailwind completion works very well, but the syntax highlighting is off. This is what I’ve been doing for now, because I prefer to work with the Tailwind completion. :)

The problem arises when I set my file type to Blade via the [Nova Blade extension](https://github.com/melvinbeemer/Blade.novaextension), which declares a `blade` syntax format. Maybe this is an issue with that other extension, and it should be declaring itself a subset of PHP? Is that possible? I’m not familiar with Nova extensions and haven’t taken the time to figure out how types are declared, so I may be barking up the wrong tree over here.

In any case, here’s a very basic Blade file. Tailwind stuff should auto-complete in the `class` declarations down in the body. It works when this is set as PHP-HTML, but fails when set as Blade.
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name') }}@hasSection('tab-title') / @yield('tab-title')@endif</title>

        <link rel="stylesheet" type="text/css" href="/css/app.css">
    </head>

    <body class="bg-gray-100">
        <div class="text-black">Hello, world.</div>
    </body>
</html>
```

**Comment by jasonplatts** [comment]
Thank you so much for the explanation @beornlake. I just pushed a version 1.2 update to the extension library that should add support for Blade files (as well as Twig and Svelte). If you have any issues, please let me know.

**Comment by beornlake** [comment]
Fantastic, thank you!

**Comment by danklammer** [comment]
Really loving this extension! Thank you, @jasonplatts! Are you able to add `.liquid` to the file types as well? The syntax is very similar to Twig from my understanding.

**Comment by jasonplatts** [comment]
Thank you for the kind words. Very happy to hear that you are finding the extension useful @danklammer! I just pushed a version 1.3 update with added support for Liquid files.

**Comment by danklammer** [comment]
Amazing! Thank you, @jasonplatts!

**Comment by jasonplatts** [comment]
Support has been added for multiple file types, so I don't think it is necessary to provide the ability to add additional file types in preferences. However, if this becomes a requested feature, it can certainly be revisited.

**Comment by MSchmidt** [comment]
I guess this depends on how much you are willing to keep updating that list. What's not working for example is tailwind classes in `.js` files. Like in next.js projects. I guess a workaround it to use `.jsx`. I have no idea why next.js is not using `.jsx` by default though.
